# #####################################################################
# Automatically generated by qmake (2.01a) sex dez 19 09:24:28 2008
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qtwiiuse.h \
    WiiThread.h \
    qtwiicontroller.h
FORMS += qtwiiuse.ui
SOURCES += main.cpp \
    qtwiiuse.cpp \
    wiiThread.cpp \
    qtwiicontroller.cpp
LIBS += -lwiiuse
